# Generated by Django 2.2.6 on 2020-02-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200212_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='judul',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pengaduan',
            name='slug',
            field=models.SlugField(blank=True, editable=False),
        ),
    ]
