# Generated by Django 2.2.6 on 2020-02-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200216_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='status_selesai',
            field=models.BooleanField(default=False),
        ),
    ]
