# Generated by Django 2.2.6 on 2020-02-16 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_pengaduan_status_selesai'),
    ]

    operations = [
        migrations.AddField(
            model_name='pengaduan',
            name='status_pengaduan',
            field=models.BooleanField(default=False),
        ),
    ]
